global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: quality-oracle
    scrape_interval: 10s
    static_configs:
      - targets:
          - morqa:8080

rule_files:
  - /etc/prometheus/rules/*.yml
